### ISSUE TITLE
API to "mark" a board location for demonstration or teaching

### ISSUE THREAD

**Issue by milescrawford** [aprescott/tenuki#46]
I would love a `markAt(x,y)` API that allowed a triangle or similar marking on an intersection. This would be useful to display possible continuations, for example, or the correct move in a go problem.

**Comment by milescrawford** [comment]
I am trying to create a pull request for this, but I cannot build even after installing deps with npm. I believe there is a babel versioning requirement that is not captured in the config:
```
babel \
		--source-maps \
		--presets es2015 \
		--out-file lib/board-state.js \
		src/board-state.js
Error: Plugin/Preset files are not allowed to export objects, only functions. In /Users/milesc/tenuki/node_modules/babel-preset-es2015/lib/index.js
    at createDescriptor (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/lib/config/config-descriptors.js:211:11)
    at createDescriptor.next (<anonymous>)
    at step (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/node_modules/gensync/index.js:261:32)
    at evaluateAsync (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/node_modules/gensync/index.js:291:5)
    at /usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/node_modules/gensync/index.js:44:11
    at Array.forEach (<anonymous>)
    at Function.async (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/node_modules/gensync/index.js:43:15)
    at Function.all (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/node_modules/gensync/index.js:216:13)
    at Generator.next (<anonymous>)
    at createDescriptors (/usr/local/Cellar/babel/7.16.0/libexec/lib/node_modules/@babel/cli/node_modules/@babel/core/lib/config/config-descriptors.js:142:41)
make: *** [lib/board-state.js] Error 1
